# Generated by Django 4.0.5 on 2022-07-04 13:42

from django.db import migrations, models
import django.utils.timezone
import mirage.fields
import tagulous.models.fields
import tagulous.models.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('KoterSDK', '0004_alter_auditlog_external_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_pcm',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='fingerpint',
            field=mirage.fields.EncryptedTextField(blank=True, max_length=512, verbose_name='Fingerprint'),
        ),
        migrations.AddField(
            model_name='contact',
            name='google_id',
            field=mirage.fields.EncryptedCharField(blank=True, max_length=80, verbose_name='Google ID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='pcm_by_phone',
            field=mirage.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='pep',
            field=models.CharField(default='PEP', max_length=560),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='externaluser',
            name='fingerprint',
            field=mirage.fields.EncryptedCharField(blank=True, max_length=512, verbose_name='Fingerprint'),
        ),
        migrations.CreateModel(
            name='Tagulous_Contact_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', null=None, to='KoterSDK.tagulous_contact_tags', verbose_name='Tags'),
        ),
    ]
